language: c

compiler:
- gcc

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y tofrodos libmysqlclient-dev libsnmp-dev help2man
- sudo ln -s /usr/bin/fromdos /usr/bin/dos2unix
- sudo ln -s /usr/bin/todos /usr/bin/unix2dos

install:
- "./bootstrap"

script:
- "./configure"
- make

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - developers@cacti.net
  slack:
    secure: 2FRfCvHDhN0kX4zsqOiz9EL106enqQyQE4+iawOyBXFKDM1QZLMWRIRu2B8GEW8w1OBBFHD7e1S0BawVlpvN++hIkaZl7rdnTuk0CRwpktQ7uVQyyybcs0zWctEIhbgzAfMRX5cez1EWPeHgqXjDbEgFA64Vu2XrRbFIe8hYUkpYxFe8dMEkAr/JCFYSWC4oOKA2OdYhs55AJ0ydZzFt/j83wKWHZ18DXgO3Y+opzDfUkY/EEUefcLmdyv7sKvqLC1QG1FhMpN2ZBGNz1umbL2WouZHZzAyw0moNSRYsOt9za5eWnLHvtoHvv0RTwe9aeab+8v7OMeeqHW/4pUocSBh/QMW5NLTPKvnMpVx0VsnVxKk0Q6e4FfpC1RioxTd+3f7v/5O6cwGOi/1SKJ7TKUX/mihHJiy3VUubcYWXhL6vymcSpM34ejOxNo9tQtnGVWz9OgqfzsNtmwMwrEGv7qeGjhIDsGmN2jOIqT/6ZA6bOyFRkQuQXWxYdngRFIUXqaGaPw1GRPAburBa4tE53b+wRXFKIH1mLsAwzk3r3db6wpVraSfxQHtpVgTU8esM7dsH3RgBDMYoiwXafJ1/GcgdfPRXZr5RAB4JOIxWJEHcULX6k+ktisPFUXzipBeXIQhXsui6d+l0WVjuy/AM3HrHFhN345flJCpHNhkUPFc=
